{
 "title": "Go Fiber API Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests (All Handlers)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rate(total_requests[1m]))" }
   ]
  },
  {
   "title": "Total Errors (All Handlers)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(total_requests_errors[1m]))"
    }
   ]
  },
  {
   "title": "Requests per Handler",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "rate(total_requests[1m])", "legendFormat": "{{handler}}" }
   ]
  },
  {
   "title": "Errors per Handler",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(total_requests_errors{handler!=\"\", type=\"Validation\"}[1m])",
     "legendFormat": "{{handler}}_{{type}}"
    },
    {
     "expr": "rate(total_requests_errors{handler!=\"\", type=\"Timeout\"}[1m])",
     "legendFormat": "{{handler}}_{{type}}"
    }
   ]
  },
  {
   "title": "Average Request Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(request_latency_sum[1m]) / rate(request_latency_count[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}