global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'proxytracker-app'
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 15s
    scrape_timeout: 10s
    follow_redirects: true
    static_configs:
      #- targets: ['172.17.0.1:8084']
      - targets: ['proxytracker-app:8084']